name: Run Test Suite

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Run tests
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_CLIENT_KEY: ${{ secrets.AWS_CLIENT_KEY }}
        AWS_USER_POOL_ID: ${{ secrets.AWS_USER_POOL_ID }}
        AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_IDENTITY_POOL_ID: ${{ secrets.AWS_IDENTITY_POOL_ID }}
        WORDNIK_API_KEY: ${{ secrets.WORDNIK_API_KEY }}
      run: sbt test
